#!/bin/bash
# Apply std patches for nvptx64 GPU compilation.
# Auto-generated by gen-patches.sh — do not edit manually.
#
# Usage: ./std-patches/apply.sh [output_dir]

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="${1:-$(dirname "$SCRIPT_DIR")/patched-std}"

SYSROOT=$(rustc +nightly --print sysroot)
SRC_DIR="$SYSROOT/lib/rustlib/src/rust/library"

if [ ! -d "$SRC_DIR" ]; then
    echo "ERROR: rust-src not found at $SRC_DIR"
    echo "Install: rustup +nightly component add rust-src"
    exit 1
fi

echo "Copying std library source from sysroot..."
rm -rf "$OUTPUT_DIR/library"
mkdir -p "$OUTPUT_DIR"
cp -r "$SRC_DIR" "$OUTPUT_DIR/library"

echo "Applying patches..."
cd "$OUTPUT_DIR/library"

echo "  [PATCH] std/src/io/stdio.rs"
patch -p0 --binary < "$SCRIPT_DIR/io_stdio.patch"

echo "  [PATCH] std/src/sys/alloc/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_alloc_mod.patch"

echo "  [PATCH] std/src/sys/fs/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_fs_mod.patch"

echo "  [PATCH] std/src/sys/io/error/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_io_error_mod.patch"

echo "  [PATCH] std/src/sys/random/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_random_mod.patch"

echo "  [PATCH] std/src/sys/stdio/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_stdio_mod.patch"

echo "  [PATCH] std/src/sys/thread_local/mod.rs"
patch -p0 --binary < "$SCRIPT_DIR/sys_thread_local_mod.patch"

echo "  [NEW]   std/src/sys/alloc/cuda.rs"
mkdir -p "std/src/sys/alloc"
cp "$SCRIPT_DIR/sys_alloc_cuda.rs" "std/src/sys/alloc/cuda.rs"

echo "  [NEW]   std/src/sys/fs/cuda.rs"
mkdir -p "std/src/sys/fs"
cp "$SCRIPT_DIR/sys_fs_cuda.rs" "std/src/sys/fs/cuda.rs"

echo "  [NEW]   std/src/sys/io/error/cuda.rs"
mkdir -p "std/src/sys/io/error"
cp "$SCRIPT_DIR/sys_io_error_cuda.rs" "std/src/sys/io/error/cuda.rs"

echo "  [NEW]   std/src/sys/stdio/cuda.rs"
mkdir -p "std/src/sys/stdio"
cp "$SCRIPT_DIR/sys_stdio_cuda.rs" "std/src/sys/stdio/cuda.rs"

echo ""
echo "Done! Patched std at: $OUTPUT_DIR/library"
echo "Build: __CARGO_TESTS_ONLY_SRC_ROOT=\"$OUTPUT_DIR/library\" cargo +nightly build --release"
