#!/bin/bash
# Apply rustc compiler patches for warp-cooperative async/await.
# Auto-generated by gen-rustc-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-rustc-patches.sh <rustc-source-dir>
#
# <rustc-source-dir> should be a fresh rustc source checkout.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/rustc-patches"
TARGET_DIR="${1:?Usage: apply-rustc-patches.sh <rustc-source-dir>}"

if [ ! -d "$TARGET_DIR/compiler" ]; then
    echo "ERROR: $TARGET_DIR does not look like a rustc source directory"
    echo "Expected: $TARGET_DIR/compiler/ to exist"
    exit 1
fi

echo "Applying rustc patches to: $TARGET_DIR"
echo ""

echo "  [PATCH] compiler/rustc_feature/src/builtin_attrs.rs"
(cd "$TARGET_DIR" && git apply "$PATCH_DIR/rustc_feature_src_builtin_attrs.patch") || \
    patch -p0 --binary -d "$TARGET_DIR" < "$PATCH_DIR/rustc_feature_src_builtin_attrs.patch"

echo "  [PATCH] compiler/rustc_mir_transform/src/lib.rs"
(cd "$TARGET_DIR" && git apply "$PATCH_DIR/rustc_mir_transform_src_lib.patch") || \
    patch -p0 --binary -d "$TARGET_DIR" < "$PATCH_DIR/rustc_mir_transform_src_lib.patch"

echo "  [PATCH] compiler/rustc_passes/src/check_attr.rs"
(cd "$TARGET_DIR" && git apply "$PATCH_DIR/rustc_passes_src_check_attr.patch") || \
    patch -p0 --binary -d "$TARGET_DIR" < "$PATCH_DIR/rustc_passes_src_check_attr.patch"

echo "  [PATCH] compiler/rustc_span/src/symbol.rs"
(cd "$TARGET_DIR" && git apply "$PATCH_DIR/rustc_span_src_symbol.patch") || \
    patch -p0 --binary -d "$TARGET_DIR" < "$PATCH_DIR/rustc_span_src_symbol.patch"

echo "  [NEW]   compiler/rustc_mir_transform/src/warp_cooperative.rs"
mkdir -p "$TARGET_DIR/compiler/rustc_mir_transform/src"
cp "$PATCH_DIR/warp_cooperative.rs" "$TARGET_DIR/compiler/rustc_mir_transform/src/warp_cooperative.rs"

echo ""
echo "Done! Patched rustc source at: $TARGET_DIR"
echo "Build: cd $TARGET_DIR && ./x.py build compiler"
