#!/bin/bash
# Apply std patches for nvptx64 GPU compilation.
# Auto-generated by gen-std-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-std-patches.sh [output_dir]
#
# Copies std source from rustc-src/ into output_dir, then applies patches.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/std-patches"
STOCK_STD="$REPO_DIR/rustc-src/library/std"
OUTPUT_DIR="${1:-$REPO_DIR/patched-std}"

if [ ! -d "$STOCK_STD" ]; then
    echo "ERROR: rustc-src/library/std/ not found."
    echo "Clone stock rustc first:"
    echo "  git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src"
    exit 1
fi

echo "Copying std source from rustc-src/..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -r "$STOCK_STD"/* "$OUTPUT_DIR/"

echo "Applying patches..."
cd "$OUTPUT_DIR"

echo "  [PATCH] src/io/stdio.rs"
patch -p1 --binary < "$PATCH_DIR/io_stdio.patch"

echo "  [PATCH] src/os/fd/raw.rs"
patch -p1 --binary < "$PATCH_DIR/os_fd_raw.patch"

echo "  [PATCH] src/sys/alloc/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_alloc_mod.patch"

echo "  [PATCH] src/sys/fs/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_fs_mod.patch"

echo "  [PATCH] src/sys/io/error/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_io_error_mod.patch"

echo "  [PATCH] src/sys/net/connection/sgx.rs"
patch -p1 --binary < "$PATCH_DIR/sys_net_connection_sgx.patch"

echo "  [PATCH] src/sys/random/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_random_mod.patch"

echo "  [PATCH] src/sys/stdio/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_stdio_mod.patch"

echo "  [PATCH] src/sys/thread_local/mod.rs"
patch -p1 --binary < "$PATCH_DIR/sys_thread_local_mod.patch"

echo "  [NEW]   src/sys/alloc/cuda.rs"
mkdir -p "src/sys/alloc"
cp "$PATCH_DIR/sys_alloc_cuda.rs" "src/sys/alloc/cuda.rs"

echo "  [NEW]   src/sys/fs/cuda.rs"
mkdir -p "src/sys/fs"
cp "$PATCH_DIR/sys_fs_cuda.rs" "src/sys/fs/cuda.rs"

echo "  [NEW]   src/sys/io/error/cuda.rs"
mkdir -p "src/sys/io/error"
cp "$PATCH_DIR/sys_io_error_cuda.rs" "src/sys/io/error/cuda.rs"

echo "  [NEW]   src/sys/stdio/cuda.rs"
mkdir -p "src/sys/stdio"
cp "$PATCH_DIR/sys_stdio_cuda.rs" "src/sys/stdio/cuda.rs"

echo "  [NEW]   src/sys/thread_local/gpu_threads.rs"
mkdir -p "src/sys/thread_local"
cp "$PATCH_DIR/sys_thread_local_gpu_threads.rs" "src/sys/thread_local/gpu_threads.rs"

echo ""
echo "Done! Patched std at: $OUTPUT_DIR"
