#!/bin/bash
# Generate rustc-patches/ from the diff between stock rustc and toolchain/.
#
# Usage: ./scripts/gen-rustc-patches.sh
#
# Like gen-std-patches.sh (for std), this diffs our modified files against the
# stock originals. Since sysroot doesn't include compiler/ source, we fetch
# stock files from GitHub using the nightly commit hash.
#
# The manifest file (rustc-patches/manifest.txt) lists which files under
# compiler/ we've modified or added. Format:
#   PATCH compiler/rustc_mir_transform/src/lib.rs
#   NEW   compiler/rustc_mir_transform/src/warp_cooperative.rs
#
# For PATCH entries: downloads stock version from GitHub, generates unified diff.
# For NEW entries: copies the file from toolchain/ into rustc-patches/.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/rustc-patches"
TOOLCHAIN_DIR="$REPO_DIR/toolchain"
MANIFEST="$PATCH_DIR/manifest.txt"

if [ ! -d "$TOOLCHAIN_DIR" ]; then
    echo "ERROR: toolchain/ directory not found."
    echo "Clone rustc source into toolchain/ first."
    exit 1
fi

if [ ! -f "$MANIFEST" ]; then
    echo "ERROR: rustc-patches/manifest.txt not found."
    echo "Create it with lines like:"
    echo "  PATCH compiler/rustc_mir_transform/src/lib.rs"
    echo "  NEW   compiler/rustc_mir_transform/src/warp_cooperative.rs"
    exit 1
fi

# Get nightly commit hash for fetching stock files
COMMIT_HASH=$(rustc +nightly --version -v 2>/dev/null | grep "commit-hash" | awk '{print $2}')
if [ -z "$COMMIT_HASH" ]; then
    echo "ERROR: Could not determine nightly commit hash."
    echo "Ensure nightly toolchain is installed: rustup toolchain install nightly"
    exit 1
fi

NIGHTLY_VER=$(rustc +nightly --version 2>/dev/null | head -1 || echo "unknown")
echo "Nightly: $NIGHTLY_VER"
echo "Commit:  $COMMIT_HASH"
echo ""

# Clean old generated patches (but not manifest.txt or PATCHES.md)
cd "$PATCH_DIR"
rm -f *.patch

PATCHES=()
NEW_FILES=()

while IFS= read -r line; do
    # Skip comments and blank lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// /}" ]] && continue

    kind=$(echo "$line" | awk '{print $1}')
    rel_path=$(echo "$line" | awk '{print $2}')

    if [ -z "$rel_path" ]; then
        echo "WARN: skipping malformed manifest line: $line"
        continue
    fi

    local_file="$TOOLCHAIN_DIR/$rel_path"
    if [ ! -f "$local_file" ]; then
        echo "WARN: $rel_path not found in toolchain/, skipping"
        continue
    fi

    case "$kind" in
        PATCH)
            # Flatten path for patch filename:
            # compiler/rustc_mir_transform/src/lib.rs → rustc_mir_transform_src_lib.patch
            flat_base=$(echo "$rel_path" | sed 's|compiler/||; s|/|_|g; s|\.rs$||')
            patch_name="${flat_base}.patch"

            # Fetch stock file from GitHub
            raw_url="https://raw.githubusercontent.com/rust-lang/rust/$COMMIT_HASH/$rel_path"
            stock_file=$(mktemp)
            if ! curl -sS -f "$raw_url" -o "$stock_file" 2>/dev/null; then
                echo "ERROR: Failed to fetch $raw_url"
                rm -f "$stock_file"
                continue
            fi

            # Generate unified diff (like gen-std-patches.sh)
            diff -u "$stock_file" "$local_file" \
                --label "a/$rel_path" --label "b/$rel_path" \
                > "$PATCH_DIR/$patch_name" || true
            rm -f "$stock_file"

            if [ -s "$PATCH_DIR/$patch_name" ]; then
                PATCHES+=("$rel_path:$patch_name")
                echo "[PATCH] $rel_path → $patch_name"
            else
                rm -f "$PATCH_DIR/$patch_name"
                echo "[SKIP]  $rel_path (no diff)"
            fi
            ;;

        NEW)
            # Copy new file from toolchain/ to rustc-patches/
            base_name=$(basename "$rel_path")
            cp "$local_file" "$PATCH_DIR/$base_name"
            NEW_FILES+=("$rel_path:$base_name")
            echo "[NEW]   $rel_path → $base_name"
            ;;

        *)
            echo "WARN: unknown kind '$kind' in manifest, skipping: $line"
            ;;
    esac
done < "$MANIFEST"

echo ""
echo "Generated ${#PATCHES[@]} patch(es), ${#NEW_FILES[@]} new file(s)."

# --- Generate apply-rustc-patches.sh ---
cat > "$SCRIPT_DIR/apply-rustc-patches.sh" << 'HEADER'
#!/bin/bash
# Apply rustc compiler patches for warp-cooperative async/await.
# Auto-generated by gen-rustc-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-rustc-patches.sh <rustc-source-dir>
#
# <rustc-source-dir> should be a fresh rustc source checkout (e.g., from
# `git clone https://github.com/rust-lang/rust.git`).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/rustc-patches"
TARGET_DIR="${1:?Usage: apply-rustc-patches.sh <rustc-source-dir>}"

if [ ! -d "$TARGET_DIR/compiler" ]; then
    echo "ERROR: $TARGET_DIR does not look like a rustc source directory"
    echo "Expected: $TARGET_DIR/compiler/ to exist"
    exit 1
fi

echo "Applying rustc patches to: $TARGET_DIR"
echo ""

HEADER

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << EOF
echo "  [PATCH] $rel_path"
(cd "\$TARGET_DIR" && git apply "\$PATCH_DIR/$patch_name") || \\
    patch -p0 --binary -d "\$TARGET_DIR" < "\$PATCH_DIR/$patch_name"

EOF
done

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    dir_path=$(dirname "$rel_path")
    cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << EOF
echo "  [NEW]   $rel_path"
mkdir -p "\$TARGET_DIR/$dir_path"
cp "\$PATCH_DIR/$flat_name" "\$TARGET_DIR/$rel_path"

EOF
done

cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << 'FOOTER'
echo ""
echo "Done! Patched rustc source at: $TARGET_DIR"
echo "Build: cd $TARGET_DIR && ./x.py build compiler"
FOOTER

chmod +x "$SCRIPT_DIR/apply-rustc-patches.sh"

# --- Generate PATCHES.md ---
cat > "$PATCH_DIR/PATCHES.md" << EOF
# Rustc Compiler Patches — WarpCooperativeTransform MIR Pass

Patches for the \`rustc_mir_transform\` crate that add warp-cooperative
async/await support for nvptx64 targets.

Baseline: \`$NIGHTLY_VER\`

## Setup

\`\`\`bash
# Clone rustc source (matching nightly)
git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src

# Apply patches
./scripts/apply-rustc-patches.sh rustc-src

# Build the patched compiler
cd rustc-src && ./x.py build compiler
\`\`\`

## Regenerate patches after editing toolchain/

\`\`\`bash
./scripts/gen-rustc-patches.sh
\`\`\`

## Modified files (patches)

EOF

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    echo "- \`$rel_path\` → \`rustc-patches/$patch_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo "" >> "$PATCH_DIR/PATCHES.md"
echo "## New files" >> "$PATCH_DIR/PATCHES.md"
echo "" >> "$PATCH_DIR/PATCHES.md"

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    echo "- \`$rel_path\` → \`rustc-patches/$flat_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo ""
echo "Updated: scripts/apply-rustc-patches.sh, rustc-patches/PATCHES.md"
echo "Done!"
