#!/bin/bash
# Generate std-patches/ from the diff between nightly sysroot and patched-std/.
#
# Usage: ./scripts/gen-std-patches.sh
#
# Compares only std/ subdirectory (we don't patch alloc/core/proc_macro).
# For modified files: generates .patch files (unified diff, -p0 relative to library/)
# For new files: copies them as .rs files with flattened names
# Regenerates scripts/apply-std-patches.sh and std-patches/PATCHES.md automatically.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/std-patches"
PATCHED_STD="$REPO_DIR/patched-std/library/std"

SYSROOT=$(rustc +nightly --print sysroot 2>/dev/null)
SYSROOT_STD="$SYSROOT/lib/rustlib/src/rust/library/std"

if [ ! -d "$SYSROOT_STD" ]; then
    echo "ERROR: rust-src not found. Install: rustup +nightly component add rust-src"
    exit 1
fi
if [ ! -d "$PATCHED_STD" ]; then
    echo "ERROR: patched-std/library/std/ not found"
    exit 1
fi

echo "Sysroot: $SYSROOT_STD"
echo "Patched: $PATCHED_STD"
echo ""

# Clean old generated files in std-patches/
cd "$PATCH_DIR"
rm -f *.patch *.rs

PATCHES=()
NEW_FILES=()

# Only scan std/ — relative paths like std/src/sys/fs/cuda.rs
while IFS= read -r patched_file; do
    rel_path="std/${patched_file#$PATCHED_STD/}"
    sysroot_file="$SYSROOT_STD/${patched_file#$PATCHED_STD/}"

    # Flatten: std/src/sys/fs/cuda.rs → sys_fs_cuda.rs
    flat_base=$(echo "$rel_path" | sed 's|std/src/||; s|/|_|g')

    if [ ! -f "$sysroot_file" ]; then
        cp "$patched_file" "$PATCH_DIR/$flat_base"
        NEW_FILES+=("$rel_path:$flat_base")
        echo "[NEW]   $rel_path → $flat_base"
    else
        if ! diff -q "$sysroot_file" "$patched_file" > /dev/null 2>&1; then
            patch_name="${flat_base%.rs}.patch"
            diff -u "$sysroot_file" "$patched_file" \
                --label "a/$rel_path" --label "b/$rel_path" \
                > "$PATCH_DIR/$patch_name" || true
            PATCHES+=("$rel_path:$patch_name")
            echo "[PATCH] $rel_path → $patch_name"
        fi
    fi
done < <(find "$PATCHED_STD" -name "*.rs" -type f | sort)

echo ""
echo "Generated ${#PATCHES[@]} patches, ${#NEW_FILES[@]} new files."

# --- Generate apply-std-patches.sh ---
cat > "$SCRIPT_DIR/apply-std-patches.sh" << 'HEADER'
#!/bin/bash
# Apply std patches for nvptx64 GPU compilation.
# Auto-generated by gen-std-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-std-patches.sh [output_dir]

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/std-patches"
OUTPUT_DIR="${1:-$REPO_DIR/patched-std}"

SYSROOT=$(rustc +nightly --print sysroot)
SRC_DIR="$SYSROOT/lib/rustlib/src/rust/library"

if [ ! -d "$SRC_DIR" ]; then
    echo "ERROR: rust-src not found at $SRC_DIR"
    echo "Install: rustup +nightly component add rust-src"
    exit 1
fi

echo "Copying std library source from sysroot..."
rm -rf "$OUTPUT_DIR/library"
mkdir -p "$OUTPUT_DIR"
cp -r "$SRC_DIR" "$OUTPUT_DIR/library"

echo "Applying patches..."
cd "$OUTPUT_DIR/library"

HEADER

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    cat >> "$SCRIPT_DIR/apply-std-patches.sh" << EOF
echo "  [PATCH] $rel_path"
patch -p1 --binary < "\$PATCH_DIR/$patch_name"

EOF
done

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    dir_path=$(dirname "$rel_path")
    cat >> "$SCRIPT_DIR/apply-std-patches.sh" << EOF
echo "  [NEW]   $rel_path"
mkdir -p "$dir_path"
cp "\$PATCH_DIR/$flat_name" "$rel_path"

EOF
done

cat >> "$SCRIPT_DIR/apply-std-patches.sh" << 'FOOTER'
echo ""
echo "Done! Patched std at: $OUTPUT_DIR/library"
echo "Build: __CARGO_TESTS_ONLY_SRC_ROOT=\"$OUTPUT_DIR/library\" cargo +nightly build --release"
FOOTER

chmod +x "$SCRIPT_DIR/apply-std-patches.sh"

# --- Generate PATCHES.md ---
NIGHTLY_VER=$(rustc +nightly --version 2>/dev/null | head -1)

cat > "$PATCH_DIR/PATCHES.md" << EOF
# Patched std — CUDA/nvptx64 patches for Rust std library

Patches for \`target_os = "cuda"\` (nvptx64-nvidia-cuda).
Nightly: \`$NIGHTLY_VER\`

## Setup

\`\`\`bash
./scripts/apply-std-patches.sh        # copies sysroot + applies patches
# Then build with:
__CARGO_TESTS_ONLY_SRC_ROOT="patched-std/library" cargo +nightly build --release
\`\`\`

## Regenerate patches after editing patched-std/

\`\`\`bash
./scripts/gen-std-patches.sh          # diffs patched-std/ vs sysroot, updates std-patches/
\`\`\`

## Modified files (patches)

EOF

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    echo "- \`$rel_path\` → \`std-patches/$patch_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo "" >> "$PATCH_DIR/PATCHES.md"
echo "## New files" >> "$PATCH_DIR/PATCHES.md"
echo "" >> "$PATCH_DIR/PATCHES.md"

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    echo "- \`$rel_path\` → \`std-patches/$flat_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo ""
echo "Updated: scripts/apply-std-patches.sh, std-patches/PATCHES.md"
echo "Done!"
