#!/bin/bash
# Generate std-patches/ by diffing patched-std/ against rustc-src/library/std/ (stock).
#
# Usage: ./scripts/gen-std-patches.sh
#
# Automatically scans src/ for differences — no manifest needed.
# - Modified files → unified diff (.patch)
# - New files (only in patched-std/) → copied as-is (.rs)
#
# Prerequisites:
#   rustc-src/  — clean rustc clone (git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src)
#   patched-std/ — std crate root with our modifications (src/...)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/std-patches"
STOCK_STD="$REPO_DIR/rustc-src/library/std"
PATCHED_STD="$REPO_DIR/patched-std"

if [ ! -d "$STOCK_STD/src" ]; then
    echo "ERROR: rustc-src/library/std/ not found."
    echo "Clone stock rustc first:"
    echo "  git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src"
    exit 1
fi

if [ ! -d "$PATCHED_STD/src" ]; then
    echo "ERROR: patched-std/src/ not found."
    echo "Run apply-std-patches.sh first, or copy std source manually."
    exit 1
fi

NIGHTLY_VER=$(rustc +nightly --version 2>/dev/null | head -1 || echo "unknown")
echo "Baseline: $NIGHTLY_VER"
echo "Stock:    $STOCK_STD"
echo "Patched:  $PATCHED_STD"
echo ""

# Clean old generated patches
cd "$PATCH_DIR"
rm -f *.patch *.rs

PATCHES=()
NEW_FILES=()

# --- Scan for modified/new .rs files under src/ ---
while IFS= read -r patched_file; do
    # rel_path = src/sys/alloc/mod.rs
    rel_path="${patched_file#$PATCHED_STD/}"
    stock_file="$STOCK_STD/$rel_path"

    # Flatten path for output filename:
    # src/sys/fs/cuda.rs → sys_fs_cuda.rs
    flat_base=$(echo "$rel_path" | sed 's|src/||; s|/|_|g')

    if [ ! -f "$stock_file" ]; then
        # New file — not in stock
        cp "$patched_file" "$PATCH_DIR/$flat_base"
        NEW_FILES+=("$rel_path:$flat_base")
        echo "[NEW]   $rel_path → $flat_base"
    else
        # Compare against stock
        if ! diff -q "$stock_file" "$patched_file" > /dev/null 2>&1; then
            patch_name="${flat_base%.rs}.patch"
            diff -u "$stock_file" "$patched_file" \
                --label "a/$rel_path" --label "b/$rel_path" \
                > "$PATCH_DIR/$patch_name" || true

            if [ -s "$PATCH_DIR/$patch_name" ]; then
                PATCHES+=("$rel_path:$patch_name")
                echo "[PATCH] $rel_path → $patch_name"
            else
                rm -f "$PATCH_DIR/$patch_name"
            fi
        fi
    fi
done < <(find "$PATCHED_STD/src" -name "*.rs" -type f | sort)

echo ""
echo "Generated ${#PATCHES[@]} patch(es), ${#NEW_FILES[@]} new file(s)."

# --- Generate apply-std-patches.sh ---
cat > "$SCRIPT_DIR/apply-std-patches.sh" << 'HEADER'
#!/bin/bash
# Apply std patches for nvptx64 GPU compilation.
# Auto-generated by gen-std-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-std-patches.sh [output_dir]
#
# Copies std source from rustc-src/ into output_dir, then applies patches.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/std-patches"
STOCK_STD="$REPO_DIR/rustc-src/library/std"
OUTPUT_DIR="${1:-$REPO_DIR/patched-std}"

if [ ! -d "$STOCK_STD" ]; then
    echo "ERROR: rustc-src/library/std/ not found."
    echo "Clone stock rustc first:"
    echo "  git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src"
    exit 1
fi

echo "Copying std source from rustc-src/..."
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"
cp -r "$STOCK_STD"/* "$OUTPUT_DIR/"

echo "Applying patches..."
cd "$OUTPUT_DIR"

HEADER

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    cat >> "$SCRIPT_DIR/apply-std-patches.sh" << EOF
echo "  [PATCH] $rel_path"
patch -p0 --binary < "\$PATCH_DIR/$patch_name"

EOF
done

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    dir_path=$(dirname "$rel_path")
    cat >> "$SCRIPT_DIR/apply-std-patches.sh" << EOF
echo "  [NEW]   $rel_path"
mkdir -p "$dir_path"
cp "\$PATCH_DIR/$flat_name" "$rel_path"

EOF
done

cat >> "$SCRIPT_DIR/apply-std-patches.sh" << 'FOOTER'
echo ""
echo "Done! Patched std at: $OUTPUT_DIR"
FOOTER

chmod +x "$SCRIPT_DIR/apply-std-patches.sh"

# --- Generate PATCHES.md ---
cat > "$PATCH_DIR/PATCHES.md" << EOF
# Patched std — CUDA/nvptx64 patches for Rust std library

Patches for \`target_os = "cuda"\` (nvptx64-nvidia-cuda).
Baseline: \`$NIGHTLY_VER\`

## Setup

\`\`\`bash
./scripts/apply-std-patches.sh    # copies rustc-src/library/std/ + applies patches → patched-std/
\`\`\`

## Regenerate patches after editing patched-std/

\`\`\`bash
./scripts/gen-std-patches.sh      # diffs patched-std/ vs rustc-src/library/std/
\`\`\`

## Modified files (patches)

EOF

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    echo "- \`$rel_path\` → \`std-patches/$patch_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo "" >> "$PATCH_DIR/PATCHES.md"
echo "## New files" >> "$PATCH_DIR/PATCHES.md"
echo "" >> "$PATCH_DIR/PATCHES.md"

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    echo "- \`$rel_path\` → \`std-patches/$flat_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo ""
echo "Updated: scripts/apply-std-patches.sh, std-patches/PATCHES.md"
echo "Done!"
