#!/bin/bash
# Generate rustc-patches/ by diffing patched-rustc/ against rustc-src/ (stock).
#
# Usage: ./scripts/gen-rustc-patches.sh
#
# Automatically scans compiler/ for differences — no manifest needed.
# - Modified files → unified diff (.patch)
# - New files (only in patched-rustc/) → copied as-is (.rs)
#
# Prerequisites:
#   rustc-src/  — clean rustc clone (git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src)
#   patched-rustc/ — copy of rustc-src/ with our modifications

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/rustc-patches"
STOCK_DIR="$REPO_DIR/rustc-src"
PATCHED_DIR="$REPO_DIR/patched-rustc"

if [ ! -d "$STOCK_DIR/compiler" ]; then
    echo "ERROR: rustc-src/ not found or missing compiler/."
    echo "Clone stock rustc first:"
    echo "  git clone --depth 1 https://github.com/rust-lang/rust.git rustc-src"
    exit 1
fi

if [ ! -d "$PATCHED_DIR/compiler" ]; then
    echo "ERROR: patched-rustc/ not found or missing compiler/."
    exit 1
fi

NIGHTLY_VER=$(rustc +nightly --version 2>/dev/null | head -1 || echo "unknown")
echo "Baseline: $NIGHTLY_VER"
echo "Stock:    $STOCK_DIR"
echo "Patched:  $PATCHED_DIR"
echo ""

# Clean old generated patches
cd "$PATCH_DIR"
rm -f *.patch *.rs

PATCHES=()
NEW_FILES=()

# --- Fast scan: use diff -rq to find only changed/new .rs files ---
# Much faster than scanning every file individually on large trees.
while IFS= read -r line; do
    if [[ "$line" == "Only in $PATCHED_DIR/"* ]]; then
        # New file — extract path
        # "Only in /path/to/patched-rustc/compiler/foo/src: bar.rs"
        dir_part=$(echo "$line" | sed "s|Only in $PATCHED_DIR/||; s|: |/|")
        rel_path="$dir_part"
        [[ "$rel_path" != *.rs ]] && continue

        base_name=$(basename "$rel_path")
        cp "$PATCHED_DIR/$rel_path" "$PATCH_DIR/$base_name"
        NEW_FILES+=("$rel_path:$base_name")
        echo "[NEW]   $rel_path → $base_name"

    elif [[ "$line" == "Files "* && "$line" == *" differ" ]]; then
        # Modified file — extract paths
        # "Files /stock/compiler/foo.rs and /patched/compiler/foo.rs differ"
        patched_file=$(echo "$line" | sed 's|.* and ||; s| differ$||')
        rel_path="${patched_file#$PATCHED_DIR/}"
        stock_file="$STOCK_DIR/$rel_path"
        [[ "$rel_path" != *.rs ]] && continue

        flat_base=$(echo "$rel_path" | sed 's|compiler/||; s|/|_|g; s|\.rs$||')
        patch_name="${flat_base}.patch"
        diff -u "$stock_file" "$patched_file" \
            --label "a/$rel_path" --label "b/$rel_path" \
            > "$PATCH_DIR/$patch_name" || true

        if [ -s "$PATCH_DIR/$patch_name" ]; then
            PATCHES+=("$rel_path:$patch_name")
            echo "[PATCH] $rel_path → $patch_name"
        else
            rm -f "$PATCH_DIR/$patch_name"
        fi
    fi
done < <(diff -rq "$STOCK_DIR/compiler" "$PATCHED_DIR/compiler" 2>/dev/null || true)

echo ""
echo "Generated ${#PATCHES[@]} patch(es), ${#NEW_FILES[@]} new file(s)."

# --- Generate apply-rustc-patches.sh ---
cat > "$SCRIPT_DIR/apply-rustc-patches.sh" << 'HEADER'
#!/bin/bash
# Apply rustc compiler patches for warp-cooperative async/await.
# Auto-generated by gen-rustc-patches.sh — do not edit manually.
#
# Usage: ./scripts/apply-rustc-patches.sh <rustc-source-dir>
#
# <rustc-source-dir> should be a fresh rustc source checkout.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
PATCH_DIR="$REPO_DIR/rustc-patches"
TARGET_DIR="${1:?Usage: apply-rustc-patches.sh <rustc-source-dir>}"

if [ ! -d "$TARGET_DIR/compiler" ]; then
    echo "ERROR: $TARGET_DIR does not look like a rustc source directory"
    echo "Expected: $TARGET_DIR/compiler/ to exist"
    exit 1
fi

echo "Applying rustc patches to: $TARGET_DIR"
echo ""

HEADER

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << EOF
echo "  [PATCH] $rel_path"
(cd "\$TARGET_DIR" && git apply "\$PATCH_DIR/$patch_name") || \\
    patch -p0 --binary -d "\$TARGET_DIR" < "\$PATCH_DIR/$patch_name"

EOF
done

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    dir_path=$(dirname "$rel_path")
    cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << EOF
echo "  [NEW]   $rel_path"
mkdir -p "\$TARGET_DIR/$dir_path"
cp "\$PATCH_DIR/$flat_name" "\$TARGET_DIR/$rel_path"

EOF
done

cat >> "$SCRIPT_DIR/apply-rustc-patches.sh" << 'FOOTER'
echo ""
echo "Done! Patched rustc source at: $TARGET_DIR"
echo "Build: cd $TARGET_DIR && ./x.py build compiler"
FOOTER

chmod +x "$SCRIPT_DIR/apply-rustc-patches.sh"

# --- Generate PATCHES.md ---
cat > "$PATCH_DIR/PATCHES.md" << EOF
# Rustc Compiler Patches — WarpCooperativeTransform MIR Pass

Patches for the \`rustc_mir_transform\` crate that add warp-cooperative
async/await support for nvptx64 targets.

Baseline: \`$NIGHTLY_VER\`

## Setup

\`\`\`bash
# Apply patches to patched-rustc/ (already done if you cloned from rustc-src/)
./scripts/apply-rustc-patches.sh patched-rustc

# Build the patched compiler
cd patched-rustc && python x.py build compiler
\`\`\`

## Regenerate patches after editing patched-rustc/

\`\`\`bash
./scripts/gen-rustc-patches.sh    # diffs patched-rustc/ vs rustc-src/
\`\`\`

## Modified files (patches)

EOF

for entry in "${PATCHES[@]}"; do
    rel_path="${entry%%:*}"
    patch_name="${entry##*:}"
    echo "- \`$rel_path\` → \`rustc-patches/$patch_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo "" >> "$PATCH_DIR/PATCHES.md"
echo "## New files" >> "$PATCH_DIR/PATCHES.md"
echo "" >> "$PATCH_DIR/PATCHES.md"

for entry in "${NEW_FILES[@]}"; do
    rel_path="${entry%%:*}"
    flat_name="${entry##*:}"
    echo "- \`$rel_path\` → \`rustc-patches/$flat_name\`" >> "$PATCH_DIR/PATCHES.md"
done

echo ""
echo "Updated: scripts/apply-rustc-patches.sh, rustc-patches/PATCHES.md"
echo "Done!"
