#!/bin/bash
# Post-process PTX files generated by rustc for the nvptx64 target.
#
# Usage:
#   ./scripts/postprocess-ptx.sh <input.ptx> [output.ptx]
#   ./scripts/postprocess-ptx.sh --all <directory>
#
# Fixes two known issues with rustc-generated PTX:
#   1. Removes `.ptr .align N` parameter annotations that CUDA PTX JIT rejects
#   2. Stubs `.extern .func` panic functions with `trap;` implementations
#
# If output is omitted, the input file is modified in-place.

set -euo pipefail

# Find python (Windows 'python3' may be a Store stub; prefer 'python' there)
PYTHON=""
for cmd in python python3; do
    if "$cmd" -c "import sys; sys.exit(0)" &>/dev/null; then
        PYTHON="$cmd"
        break
    fi
done
if [ -z "$PYTHON" ]; then
    echo "ERROR: Python 3 not found. Install Python 3 and ensure it's on PATH." >&2
    exit 1
fi

# ============================================================
# Post-processing transformations
# ============================================================

postprocess_ptx() {
    local input="$1"
    local output="$2"

    if [ ! -f "$input" ]; then
        echo "ERROR: File not found: $input" >&2
        return 1
    fi

    local tmpfile
    tmpfile=$(mktemp)
    cp "$input" "$tmpfile"

    # Run all transformations in a single Python script for reliability
    "$PYTHON" - "$tmpfile" << 'PYEOF'
import re, sys

filepath = sys.argv[1]
with open(filepath, 'r') as f:
    content = f.read()

original = content

# --- Fix 1: Remove `.ptr .align N` from parameter declarations ---
# LLVM NVPTX backend emits `.param .u64 .ptr .align 1 name` for raw pointer params.
# CUDA PTX JIT rejects this annotation. Remove it.
content = re.sub(r'\.ptr\s+\.align\s+\d+', '', content)

# --- Fix 2: Stub extern panic functions ---
# Async fn coroutines emit `.extern .func panic_const_async_fn_resumed(...)`.
# These span multiple lines when params are listed. Replace with trap; stubs.
#
# Pattern: .extern .func NAME\n(\nparams...\n)\n;
# or:      .extern .func NAME ;

extern_pattern = re.compile(
    r'\.extern\s+\.func\s+(\S+)\s*'   # .extern .func NAME
    r'(\([^)]*\))?\s*;',              # optional (params) then ;
    re.DOTALL
)

def replace_extern(m):
    name = m.group(1)
    params = m.group(2)  # "(params)" or None

    # Only stub panic/abort-related functions
    if 'panic' not in name and 'abort' not in name:
        return m.group(0)  # leave non-panic externs alone

    if params:
        params_inner = params.strip()
    else:
        params_inner = '()'

    return f'.visible .func {name}{params_inner}\n{{\n\ttrap;\n\tret;\n}}'

content = extern_pattern.sub(replace_extern, content)

# Write result
with open(filepath, 'w') as f:
    f.write(content)

# Report changes
fix1_count = len(re.findall(r'\.ptr\s+\.align\s+\d+', original))
fix2_count = len([m for m in extern_pattern.finditer(original)
                  if 'panic' in m.group(1) or 'abort' in m.group(1)])

if fix1_count or fix2_count:
    parts = []
    if fix1_count:
        parts.append(f'{fix1_count} .ptr .align removed')
    if fix2_count:
        parts.append(f'{fix2_count} panic extern(s) stubbed')
    print(f'  Fixed: {", ".join(parts)}', file=sys.stderr)
else:
    print('  No changes needed', file=sys.stderr)
PYEOF

    # Write output
    if [ "$output" = "$input" ]; then
        mv "$tmpfile" "$output"
    else
        cp "$tmpfile" "$output"
        rm -f "$tmpfile"
    fi
}

# ============================================================
# Main entry point
# ============================================================

if [ "${1:-}" = "--all" ]; then
    DIR="${2:?Usage: postprocess-ptx.sh --all <directory>}"
    if [ ! -d "$DIR" ]; then
        echo "ERROR: Directory not found: $DIR" >&2
        exit 1
    fi

    COUNT=0
    while IFS= read -r -d '' ptxfile; do
        echo "Processing: $ptxfile"
        postprocess_ptx "$ptxfile" "$ptxfile"
        COUNT=$((COUNT + 1))
    done < <(find "$DIR" -name '*.ptx' -print0)

    echo "Done: processed $COUNT PTX file(s)"

elif [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
    echo "Usage:"
    echo "  $0 <input.ptx> [output.ptx]   Process a single PTX file"
    echo "  $0 --all <directory>           Process all .ptx files in directory"
    echo ""
    echo "Fixes:"
    echo "  1. Removes .ptr .align N parameter annotations (CUDA JIT compat)"
    echo "  2. Stubs .extern .func panic_* with trap; (missing core::panicking)"

elif [ -n "${1:-}" ]; then
    INPUT="$1"
    OUTPUT="${2:-$1}"
    echo "Processing: $INPUT → $OUTPUT"
    postprocess_ptx "$INPUT" "$OUTPUT"
    echo "Done."

else
    echo "Usage: $0 <input.ptx> [output.ptx]" >&2
    echo "       $0 --all <directory>" >&2
    exit 1
fi
