use anyhow::{Context, Result};
use cudarc::driver::{CudaDevice, CudaSlice, LaunchAsync, LaunchConfig};
use std::sync::Arc;

// Embed the compiled PTX at build time.
// The PTX file is generated by compiling crates/gpu-kernel with:
//   cargo +nightly rustc --release --target nvptx64-nvidia-cuda -Zbuild-std=core \
//       -- --emit=asm -C linker=echo
// and then copied to crates/gpu-host/kernel.ptx
const KERNEL_PTX: &str = include_str!("../kernel.ptx");

fn run_write_thread_idx(dev: Arc<CudaDevice>) -> Result<()> {
    const N: usize = 64;

    // Load the PTX module and get a reference to the kernel function.
    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    dev.load_ptx(ptx, "kernel", &["write_thread_idx"])
        .context("failed to load PTX module")?;

    let f = dev
        .get_func("kernel", "write_thread_idx")
        .context("kernel function not found")?;

    // Allocate device memory: N u32 values, initialized to zero.
    let mut output: CudaSlice<u32> = dev
        .alloc_zeros::<u32>(N)
        .context("failed to allocate device buffer")?;

    // Launch: 1 block of 64 threads.
    let cfg = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (N as u32, 1, 1),
        shared_mem_bytes: 0,
    };
    unsafe {
        f.launch(cfg, (&mut output, N as u32))
            .context("kernel launch failed")?;
    }

    // Copy result back to host.
    let result: Vec<u32> = dev
        .dtoh_sync_copy(&output)
        .context("failed to copy results to host")?;

    println!("write_thread_idx output ({} elements):", N);
    println!("  {:?}", &result[..N.min(16)]);

    // Verify: result[i] should equal i.
    for (i, &val) in result.iter().enumerate() {
        if val != i as u32 {
            anyhow::bail!(
                "verification failed at index {}: expected {}, got {}",
                i,
                i,
                val
            );
        }
    }
    println!("  Verification PASSED: all {} elements correct", N);
    Ok(())
}

fn run_vector_add(dev: Arc<CudaDevice>) -> Result<()> {
    const N: usize = 128;

    let a_host: Vec<f32> = (0..N).map(|i| i as f32).collect();
    let b_host: Vec<f32> = (0..N).map(|i| (N - i) as f32).collect();

    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    // Module may already be loaded; ignore error if so.
    let _ = dev.load_ptx(ptx, "kernel", &["vector_add"]);

    let f = dev
        .get_func("kernel", "vector_add")
        .context("vector_add function not found")?;

    let a_dev: CudaSlice<f32> = dev.htod_sync_copy(&a_host).context("htod a")?;
    let b_dev: CudaSlice<f32> = dev.htod_sync_copy(&b_host).context("htod b")?;
    let mut c_dev: CudaSlice<f32> = dev.alloc_zeros::<f32>(N).context("alloc c")?;

    let cfg = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (N as u32, 1, 1),
        shared_mem_bytes: 0,
    };
    unsafe {
        f.launch(cfg, (&a_dev, &b_dev, &mut c_dev, N as u32))
            .context("vector_add launch failed")?;
    }

    let c_host: Vec<f32> = dev
        .dtoh_sync_copy(&c_dev)
        .context("dtoh c")?;

    println!("\nvector_add output (first 16 of {} elements):", N);
    println!("  {:?}", &c_host[..16]);

    // Each element should equal a[i] + b[i] = i + (N - i) = N = 128.0
    let expected = N as f32;
    for (i, &val) in c_host.iter().enumerate() {
        if (val - expected).abs() > 1e-5 {
            anyhow::bail!(
                "vector_add verification failed at index {}: expected {}, got {}",
                i,
                expected,
                val
            );
        }
    }
    println!("  Verification PASSED: all {} elements equal {}", N, expected);
    Ok(())
}

fn main() -> Result<()> {
    println!("=== GPU Kernel Execution Test ===\n");

    // Initialize CUDA device 0.
    let dev = CudaDevice::new(0).context("failed to initialize CUDA device 0")?;
    println!("CUDA device initialized successfully");

    run_write_thread_idx(Arc::clone(&dev))?;
    run_vector_add(Arc::clone(&dev))?;

    println!("\nAll tests PASSED.");
    Ok(())
}
