use anyhow::{Context, Result};
use cudarc::driver::{CudaDevice, CudaSlice, LaunchAsync, LaunchConfig};
use cudarc::driver::sys::{self, lib as cuda_lib};
use std::sync::Arc;
use std::sync::atomic::{AtomicU32, Ordering};

// Embed the compiled PTX at build time.
// The PTX file is generated by compiling crates/gpu-kernel with:
//   cargo +nightly rustc --release --target nvptx64-nvidia-cuda -Zbuild-std=core \
//       -- --emit=asm -C linker=echo -C target-cpu=sm_86
// and then copied to crates/gpu-host/kernel.ptx
const KERNEL_PTX: &str = include_str!("../kernel.ptx");

fn run_write_thread_idx(dev: Arc<CudaDevice>) -> Result<()> {
    const N: usize = 64;

    // Load the PTX module and get a reference to the kernel function.
    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    dev.load_ptx(ptx, "kernel", &["write_thread_idx"])
        .context("failed to load PTX module")?;

    let f = dev
        .get_func("kernel", "write_thread_idx")
        .context("kernel function not found")?;

    // Allocate device memory: N u32 values, initialized to zero.
    let mut output: CudaSlice<u32> = dev
        .alloc_zeros::<u32>(N)
        .context("failed to allocate device buffer")?;

    // Launch: 1 block of 64 threads.
    let cfg = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (N as u32, 1, 1),
        shared_mem_bytes: 0,
    };
    unsafe {
        f.launch(cfg, (&mut output, N as u32))
            .context("kernel launch failed")?;
    }

    // Copy result back to host.
    let result: Vec<u32> = dev
        .dtoh_sync_copy(&output)
        .context("failed to copy results to host")?;

    println!("write_thread_idx output ({} elements):", N);
    println!("  {:?}", &result[..N.min(16)]);

    // Verify: result[i] should equal i.
    for (i, &val) in result.iter().enumerate() {
        if val != i as u32 {
            anyhow::bail!(
                "verification failed at index {}: expected {}, got {}",
                i,
                i,
                val
            );
        }
    }
    println!("  Verification PASSED: all {} elements correct", N);
    Ok(())
}

fn run_vector_add(dev: Arc<CudaDevice>) -> Result<()> {
    const N: usize = 128;

    let a_host: Vec<f32> = (0..N).map(|i| i as f32).collect();
    let b_host: Vec<f32> = (0..N).map(|i| (N - i) as f32).collect();

    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    // Module may already be loaded; ignore error if so.
    let _ = dev.load_ptx(ptx, "kernel", &["vector_add"]);

    let f = dev
        .get_func("kernel", "vector_add")
        .context("vector_add function not found")?;

    let a_dev: CudaSlice<f32> = dev.htod_sync_copy(&a_host).context("htod a")?;
    let b_dev: CudaSlice<f32> = dev.htod_sync_copy(&b_host).context("htod b")?;
    let mut c_dev: CudaSlice<f32> = dev.alloc_zeros::<f32>(N).context("alloc c")?;

    let cfg = LaunchConfig {
        grid_dim: (1, 1, 1),
        block_dim: (N as u32, 1, 1),
        shared_mem_bytes: 0,
    };
    unsafe {
        f.launch(cfg, (&a_dev, &b_dev, &mut c_dev, N as u32))
            .context("vector_add launch failed")?;
    }

    let c_host: Vec<f32> = dev
        .dtoh_sync_copy(&c_dev)
        .context("dtoh c")?;

    println!("\nvector_add output (first 16 of {} elements):", N);
    println!("  {:?}", &c_host[..16]);

    // Each element should equal a[i] + b[i] = i + (N - i) = N = 128.0
    let expected = N as f32;
    for (i, &val) in c_host.iter().enumerate() {
        if (val - expected).abs() > 1e-5 {
            anyhow::bail!(
                "vector_add verification failed at index {}: expected {}, got {}",
                i,
                expected,
                val
            );
        }
    }
    println!("  Verification PASSED: all {} elements equal {}", N, expected);
    Ok(())
}

/// Step 1 + Step 3: Test inline PTX asm kernels and inspect their PTX output.
/// This verifies the kernels launch without error (functional test).
/// The PTX content is verified statically in the findings document.
fn run_asm_smoke_tests(dev: Arc<CudaDevice>) -> Result<()> {
    println!("\n--- Step 1 / Step 3: Inline PTX asm smoke tests ---");

    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    let _ = dev.load_ptx(ptx, "kernel", &[
        "test_asm_membar_sys",
        "test_asm_st_release_sys",
        "test_asm_ld_acquire_sys",
        "test_asm_cas_sys",
        "test_nvvm_membar_sys",
        "test_nvvm_atomic_add_sys",
        "test_read_volatile",
        "test_write_volatile",
    ]);

    // test_asm_membar_sys: 4 threads write 0xDEADBEEF to output
    {
        let f = dev.get_func("kernel", "test_asm_membar_sys")
            .context("test_asm_membar_sys not found")?;
        let mut out: CudaSlice<u32> = dev.alloc_zeros::<u32>(4).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (4,1,1), shared_mem_bytes: 0 };
        unsafe { f.launch(cfg, (&mut out, 4u32)).context("launch test_asm_membar_sys")? };
        let result = dev.dtoh_sync_copy(&out).context("dtoh")?;
        for &v in &result {
            if v != 0xDEAD_BEEFu32 {
                anyhow::bail!("test_asm_membar_sys: expected 0xDEADBEEF, got 0x{:08X}", v);
            }
        }
        println!("  test_asm_membar_sys: PASSED (membar.sys + st.global.b32 works, result = 0xDEADBEEF)");
    }

    // test_asm_st_release_sys: write value 42 to a device buffer
    {
        let f = dev.get_func("kernel", "test_asm_st_release_sys")
            .context("test_asm_st_release_sys not found")?;
        let mut out: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };
        unsafe { f.launch(cfg, (&mut out, 42u32)).context("launch test_asm_st_release_sys")? };
        let result = dev.dtoh_sync_copy(&out).context("dtoh")?;
        if result[0] != 42 {
            anyhow::bail!("test_asm_st_release_sys: expected 42, got {}", result[0]);
        }
        println!("  test_asm_st_release_sys: PASSED (st.release.sys.global.u32 works, wrote 42)");
    }

    // test_asm_ld_acquire_sys: read from device buffer via ld.acquire.sys
    {
        let f = dev.get_func("kernel", "test_asm_ld_acquire_sys")
            .context("test_asm_ld_acquire_sys not found")?;
        let src: CudaSlice<u32> = dev.htod_sync_copy(&[99u32]).context("htod src")?;
        let mut dst: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };
        unsafe { f.launch(cfg, (&src, &mut dst)).context("launch test_asm_ld_acquire_sys")? };
        let result = dev.dtoh_sync_copy(&dst).context("dtoh")?;
        if result[0] != 99 {
            anyhow::bail!("test_asm_ld_acquire_sys: expected 99, got {}", result[0]);
        }
        println!("  test_asm_ld_acquire_sys: PASSED (ld.acquire.sys.global.u32 works, read 99)");
    }

    // test_asm_cas_sys: CAS on device memory
    {
        let f = dev.get_func("kernel", "test_asm_cas_sys")
            .context("test_asm_cas_sys not found")?;
        let mut target: CudaSlice<u32> = dev.htod_sync_copy(&[7u32]).context("htod target")?;
        let mut result_out: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc result")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };
        // CAS(target, expected=7, desired=99) → should succeed, return old=7, target becomes 99
        unsafe {
            f.launch(cfg, (&mut target, 7u32, 99u32, &mut result_out))
                .context("launch test_asm_cas_sys")?;
        }
        let old_val = dev.dtoh_sync_copy(&result_out).context("dtoh old_val")?[0];
        let new_val = dev.dtoh_sync_copy(&target).context("dtoh target")?[0];
        if old_val != 7 || new_val != 99 {
            anyhow::bail!(
                "test_asm_cas_sys: expected old=7 new=99, got old={} new={}",
                old_val, new_val
            );
        }
        println!("  test_asm_cas_sys: PASSED (atom.cas.sys.global.b32 works, old=7→new=99)");
    }

    // test_nvvm_membar_sys: NVVM intrinsic path
    {
        let f = dev.get_func("kernel", "test_nvvm_membar_sys")
            .context("test_nvvm_membar_sys not found")?;
        let mut flag: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };
        unsafe { f.launch(cfg, (&mut flag,)).context("launch test_nvvm_membar_sys")? };
        let result = dev.dtoh_sync_copy(&flag).context("dtoh")?;
        if result[0] != 1 {
            anyhow::bail!("test_nvvm_membar_sys: expected 1, got {}", result[0]);
        }
        println!("  test_nvvm_membar_sys: PASSED (llvm.nvvm.membar.sys intrinsic works)");
    }

    // test_nvvm_atomic_add_sys: NVVM atomic add
    {
        let f = dev.get_func("kernel", "test_nvvm_atomic_add_sys")
            .context("test_nvvm_atomic_add_sys not found")?;
        let mut counter: CudaSlice<i32> = dev.htod_sync_copy(&[10i32]).context("htod")?;
        let mut result_out: CudaSlice<i32> = dev.alloc_zeros::<i32>(1).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };
        unsafe {
            f.launch(cfg, (&mut counter, 5i32, &mut result_out))
                .context("launch test_nvvm_atomic_add_sys")?;
        }
        let old_val = dev.dtoh_sync_copy(&result_out).context("dtoh old")?[0];
        let new_val = dev.dtoh_sync_copy(&counter).context("dtoh counter")?[0];
        if old_val != 10 || new_val != 15 {
            anyhow::bail!(
                "test_nvvm_atomic_add_sys: expected old=10 new=15, got old={} new={}",
                old_val, new_val
            );
        }
        println!("  test_nvvm_atomic_add_sys: PASSED (llvm.nvvm.atomic.add.gen.i.sys works, 10+5=15)");
    }

    // test_read_volatile / test_write_volatile
    {
        let f_write = dev.get_func("kernel", "test_write_volatile")
            .context("test_write_volatile not found")?;
        let f_read = dev.get_func("kernel", "test_read_volatile")
            .context("test_read_volatile not found")?;

        let mut buf: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc")?;
        let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (1,1,1), shared_mem_bytes: 0 };

        // Write 0xCAFEBABE via st.volatile.global
        unsafe {
            f_write.launch(cfg, (&mut buf, 0xCAFE_BABEu32))
                .context("launch test_write_volatile")?;
        }

        // Read back via ld.volatile.global
        let mut dst: CudaSlice<u32> = dev.alloc_zeros::<u32>(1).context("alloc")?;
        unsafe {
            f_read.launch(cfg, (&buf, &mut dst))
                .context("launch test_read_volatile")?;
        }

        let result = dev.dtoh_sync_copy(&dst).context("dtoh")?;
        if result[0] != 0xCAFE_BABEu32 {
            anyhow::bail!(
                "test_read/write_volatile: expected 0xCAFEBABE, got 0x{:08X}",
                result[0]
            );
        }
        println!("  test_write_volatile + test_read_volatile: PASSED");
        println!("    st.volatile.global.b32 wrote 0xCAFEBABE, ld.volatile.global.b32 read it back");
    }

    println!("  All asm smoke tests PASSED.");
    Ok(())
}

/// Step 5: Integration test using mapped host memory for GPU-CPU communication.
///
/// Uses cuMemHostAlloc(CU_MEMHOSTALLOC_DEVICEMAP) to allocate pinned host memory
/// accessible from both GPU and CPU. The GPU writes a value and sets a flag using
/// st.release.sys.global.u32. The CPU polls the flag (with a timeout) and verifies
/// the written value.
///
/// This is the canonical GPU-CPU communication pattern required for the hostcall protocol.
fn run_integration_sys_store(dev: Arc<CudaDevice>) -> Result<()> {
    println!("\n--- Step 5: Integration test (GPU st.release.sys → CPU poll) ---");

    const EXPECTED_VALUE: u32 = 0xABCD_1234;
    const TIMEOUT_ITERS: usize = 100_000_000;

    // Allocate two pinned, device-mapped host memory locations:
    //   - data_host_ptr: the "data" written by the GPU
    //   - flag_host_ptr: the "ready" flag written by the GPU after data
    //
    // Both are zero-initialized.
    let (data_host_ptr, data_dev_ptr) = unsafe { alloc_mapped_u32(&dev)? };
    let (flag_host_ptr, flag_dev_ptr) = unsafe { alloc_mapped_u32(&dev)? };

    // Initialize to 0
    unsafe {
        std::ptr::write_volatile(data_host_ptr, 0u32);
        std::ptr::write_volatile(flag_host_ptr, 0u32);
    }

    let ptx = cudarc::nvrtc::Ptx::from_src(KERNEL_PTX);
    let _ = dev.load_ptx(ptx, "kernel", &["integration_sys_store"]);
    let f = dev.get_func("kernel", "integration_sys_store")
        .context("integration_sys_store not found")?;

    // Launch 1 block of 32 threads. Thread 0 does the writes.
    let cfg = LaunchConfig { grid_dim: (1,1,1), block_dim: (32,1,1), shared_mem_bytes: 0 };

    println!("  Launching GPU kernel (thread 0 writes data + flag to pinned memory)...");
    unsafe {
        // Pass raw device pointers as u64 (the GPU kernel expects *mut u32)
        let data_u64 = data_dev_ptr as u64;
        let flag_u64 = flag_dev_ptr as u64;
        f.launch(cfg, (data_u64, flag_u64, EXPECTED_VALUE, 32u32))
            .context("integration_sys_store launch failed")?;
    }

    println!("  Host polling flag (with acquire semantics via AtomicU32::load)...");
    let flag_atomic = unsafe { &*(flag_host_ptr as *const AtomicU32) };
    let data_atomic = unsafe { &*(data_host_ptr as *const AtomicU32) };

    let mut flag_val = 0u32;
    for i in 0..TIMEOUT_ITERS {
        flag_val = flag_atomic.load(Ordering::Acquire);
        if flag_val == 1 {
            println!("  Flag became 1 after {} poll iterations.", i);
            break;
        }
        if i % 10_000_000 == 0 && i > 0 {
            println!("  ... still polling, iteration {}", i);
        }
    }

    if flag_val != 1 {
        // Free pinned memory before returning
        unsafe {
            free_mapped_mem(data_host_ptr)?;
            free_mapped_mem(flag_host_ptr)?;
        }
        anyhow::bail!("Integration test TIMEOUT: flag never became 1 after {} iters", TIMEOUT_ITERS);
    }

    // Read the data value — guaranteed visible because flag was 1 (release/acquire pair)
    let data_val = data_atomic.load(Ordering::Acquire);

    // Free mapped memory
    unsafe {
        free_mapped_mem(data_host_ptr)?;
        free_mapped_mem(flag_host_ptr)?;
    }

    if data_val != EXPECTED_VALUE {
        anyhow::bail!(
            "Integration test FAILED: expected data=0x{:08X}, got 0x{:08X}",
            EXPECTED_VALUE, data_val
        );
    }

    println!("  Integration test PASSED!");
    println!("    GPU wrote data=0x{:08X} then set flag=1 via st.release.sys", EXPECTED_VALUE);
    println!("    CPU saw flag=1 and read data=0x{:08X} correctly", data_val);
    println!("    Protocol: GPU st.release.sys → CPU Ordering::Acquire poll works correctly");
    Ok(())
}

/// Allocates a single u32 of pinned, device-mapped host memory.
/// Returns (host_ptr, device_ptr).
unsafe fn alloc_mapped_u32(_dev: &Arc<CudaDevice>) -> Result<(*mut u32, sys::CUdeviceptr)> {
    let cu = cuda_lib();

    let mut host_ptr: *mut std::ffi::c_void = std::ptr::null_mut();

    // CU_MEMHOSTALLOC_DEVICEMAP = 0x02 → allow GPU to access this memory
    let flags = sys::CU_MEMHOSTALLOC_DEVICEMAP;
    let result = cu.cuMemHostAlloc(&mut host_ptr, std::mem::size_of::<u32>(), flags);
    if result != sys::CUresult::CUDA_SUCCESS {
        anyhow::bail!("cuMemHostAlloc failed: {:?}", result);
    }

    // Get the device-side pointer for the same memory
    let mut dev_ptr: sys::CUdeviceptr = 0;
    let result = cu.cuMemHostGetDevicePointer_v2(&mut dev_ptr, host_ptr, 0);
    if result != sys::CUresult::CUDA_SUCCESS {
        // Free host mem before error
        cu.cuMemFreeHost(host_ptr);
        anyhow::bail!("cuMemHostGetDevicePointer_v2 failed: {:?}", result);
    }

    Ok((host_ptr as *mut u32, dev_ptr))
}

/// Frees pinned host memory allocated with cuMemHostAlloc.
unsafe fn free_mapped_mem(host_ptr: *mut u32) -> Result<()> {
    let cu = cuda_lib();
    let result = cu.cuMemFreeHost(host_ptr as *mut std::ffi::c_void);
    if result != sys::CUresult::CUDA_SUCCESS {
        anyhow::bail!("cuMemFreeHost failed: {:?}", result);
    }
    Ok(())
}

fn main() -> Result<()> {
    println!("=== GPU Kernel Execution Test ===\n");

    // Initialize CUDA device 0.
    let dev = CudaDevice::new(0).context("failed to initialize CUDA device 0")?;
    println!("CUDA device initialized successfully");

    run_write_thread_idx(Arc::clone(&dev))?;
    run_vector_add(Arc::clone(&dev))?;
    run_asm_smoke_tests(Arc::clone(&dev))?;
    run_integration_sys_store(Arc::clone(&dev))?;

    println!("\nAll tests PASSED.");
    Ok(())
}
