#![allow(clippy::needless_range_loop)]
mod error;
mod hostcall;
mod mapped_mem;
mod tests_basic;
mod tests_benchmark;
mod tests_compute;
mod tests_hostcall;
mod tests_pipeline;
mod tests_scaling;
mod tests_std;
mod tests_warp;

use cudarc::driver::CudaDevice;
use error::{GpuHostError, Result};
use std::sync::Arc;

// Embed the compiled PTX at build time.
// The PTX file is generated by compiling crates/gpu-kernel with:
//   cargo +nightly rustc --release --target nvptx64-nvidia-cuda -Zbuild-std=core \
//       -- --emit=asm -C linker=echo -C target-cpu=sm_86
// and then copied to crates/gpu-host/kernel.ptx
const KERNEL_PTX: &str = include_str!("../kernel.ptx");

// Embassy test PTX — compiled from crates/embassy-test with fat LTO
const EMBASSY_PTX: &str = include_str!("../embassy_test.ptx");

// Async hostcall test PTX — compiled from crates/async-hostcall-test with fat LTO
const ASYNC_HOSTCALL_PTX: &str = include_str!("../async_hostcall_test.ptx");

// Std-build-test PTX — compiled from crates/std-build-test with -Zbuild-std=std + patched std
const STD_BUILD_TEST_PTX: &str = include_str!("../std_build_test.ptx");

// Async pipeline test PTX — compiled from crates/async-pipeline-test with fat LTO
const ASYNC_PIPELINE_PTX: &str = include_str!("../async_pipeline_test.ptx");

// Multi-warp scaling test PTX — compiled from crates/multi-warp-test with fat LTO
const MULTI_WARP_PTX: &str = include_str!("../multi_warp_test.ptx");

fn main() -> Result<()> {
    println!("=== GPU Kernel Execution Test ===\n");

    let dev = CudaDevice::new(0).map_err(GpuHostError::CudaInit)?;
    println!("CUDA device initialized successfully");

    tests_basic::run_write_thread_idx(Arc::clone(&dev))?;
    tests_basic::run_vector_add(Arc::clone(&dev))?;
    tests_basic::run_asm_smoke_tests(Arc::clone(&dev))?;
    tests_basic::run_integration_sys_store(Arc::clone(&dev))?;
    tests_basic::run_u64_atomics_tests(Arc::clone(&dev))?;
    tests_basic::run_warp_intrinsics_tests(Arc::clone(&dev))?;

    // Hostcall tests (hostcall.4)
    tests_hostcall::run_hostcall_print_hello(Arc::clone(&dev))?;
    tests_hostcall::run_hostcall_print_multi(Arc::clone(&dev), 4)?;

    // Embassy async/await tests (async-runtime.3)
    tests_hostcall::run_embassy_immediate(Arc::clone(&dev))?;
    tests_hostcall::run_embassy_countdown(Arc::clone(&dev))?;
    tests_hostcall::run_embassy_two_task(Arc::clone(&dev))?;
    tests_hostcall::run_sync_countdown(Arc::clone(&dev))?;

    // File I/O test (gpu-std.3)
    tests_hostcall::run_hostcall_file_test(Arc::clone(&dev))?;

    // Async hostcall tests (integration.1)
    tests_hostcall::run_async_hostcall_single(Arc::clone(&dev))?;
    tests_hostcall::run_async_hostcall_two(Arc::clone(&dev))?;

    // futures_util::future::join on GPU (integration.2)
    tests_hostcall::run_futures_join(Arc::clone(&dev))?;

    // GPU Instant + Time test (gpu-std.4)
    tests_hostcall::run_hostcall_time_test(Arc::clone(&dev))?;

    // Std-build-test (integration.3): -Zbuild-std=std on GPU
    tests_std::run_std_build_test(Arc::clone(&dev))?;

    // Dynamic allocation stress test (product.1)
    tests_std::run_dynamic_alloc_test(Arc::clone(&dev))?;

    // Hostcall latency benchmark (benchmark.2) — run before PAL tests
    tests_benchmark::run_hostcall_latency_benchmark(Arc::clone(&dev))?;

    // Warp divergence measurement (warp-future.2)
    tests_benchmark::run_warp_divergence_measurement(Arc::clone(&dev))?;

    // Bulk data transfer test (large-payload.3)
    tests_pipeline::run_bulk_io_test(Arc::clone(&dev))?;

    // Per-block sharding test (per-block-sharding.2)
    tests_pipeline::run_sharded_hostcall_test(Arc::clone(&dev))?;

    // Sharding benchmark (per-block-sharding.3)
    tests_benchmark::run_sharding_benchmark(Arc::clone(&dev))?;

    // Parallel file grep demo (product.8)
    tests_pipeline::run_parallel_grep_test(Arc::clone(&dev))?;

    // Warp intrinsics test (warp-future.3): syncwarp + shfl.sync.idx
    tests_warp::run_warp_intrinsics_test(Arc::clone(&dev))?;

    // WarpFuture PoC test (warp-future.4)
    tests_warp::run_warp_future_print_test(Arc::clone(&dev))?;

    // WarpFuture multi-hostcall test (warp-future.6)
    tests_warp::run_warp_future_multi_print_test(Arc::clone(&dev))?;

    // WarpFuture proc macro test (warp-future.5)
    tests_warp::run_warp_macro_print_test(Arc::clone(&dev))?;

    // WarpFuture if/else test (warp-cfg.2)
    tests_warp::run_warp_cfg_if_else_test(Arc::clone(&dev))?;

    // WarpFuture loop/break test (warp-cfg.3)
    tests_warp::run_warp_cfg_loop_test(Arc::clone(&dev))?;

    // WarpFuture match test (warp-cfg.4)
    tests_warp::run_warp_cfg_match_test(Arc::clone(&dev))?;

    // WarpFuture nested control flow test (warp-cfg.5)
    tests_warp::run_warp_cfg_nested_test(Arc::clone(&dev))?;

    // Hybrid executor test (hybrid-executor.1)
    tests_warp::run_hybrid_executor_test(Arc::clone(&dev))?;

    // Hybrid stress test (hybrid-executor.2)
    tests_warp::run_hybrid_stress_test(Arc::clone(&dev))?;

    // f32 math validation (ml-workload.1)
    tests_compute::run_f32_math_test(Arc::clone(&dev))?;

    // Vector similarity search (ml-workload.2)
    tests_compute::run_vector_search_test(Arc::clone(&dev))?;

    // Batch vector search (ml-workload.3)
    tests_compute::run_batch_search_test(Arc::clone(&dev))?;

    // File transform pipeline (async-pipeline.1+2)
    tests_pipeline::run_file_transform_test(Arc::clone(&dev))?;

    // Branching pipeline (async-pipeline.3)
    tests_pipeline::run_branching_pipeline_test(Arc::clone(&dev))?;

    // Pipelined I/O + compute (async-pipeline.4)
    tests_pipeline::run_pipelined_compute_test(Arc::clone(&dev))?;

    // Warp-scale Embassy test (async-pipeline.5)
    tests_pipeline::run_warp_scale_async_test(Arc::clone(&dev))?;

    // Autonomous pipeline test (gpu-compute.2)
    tests_pipeline::run_autonomous_pipeline_test(Arc::clone(&dev))?;

    // Tensor Core MMA test (gpu-compute.3)
    tests_compute::run_mma_test(Arc::clone(&dev))?;

    // Shared memory + bar.sync test (gpu-compute.4)
    tests_compute::run_shared_memory_test(Arc::clone(&dev))?;

    // Tiled GEMM test (gpu-compute.5)
    tests_compute::run_tiled_gemm_test(Arc::clone(&dev))?;

    // MMA fragment mapping test (gpu-pipeline.1)
    tests_compute::run_mma_mapped_test(Arc::clone(&dev))?;

    // Softmax test (gpu-compute.6)
    tests_compute::run_softmax_test(Arc::clone(&dev))?;

    // GPU panic handler test (gpu-panic.2) — MUST BE LAST
    // since trap instruction calls process::exit(0)
    tests_pipeline::run_panic_test(Arc::clone(&dev))?;

    // PAL stdout routing test (std-pal.1)
    tests_std::run_std_println_test(Arc::clone(&dev))?;

    // PAL stdin routing test (std-pal.2)
    tests_std::run_std_stdin_test(Arc::clone(&dev))?;

    // Multi-warp scaling test (product.3)
    tests_scaling::run_multi_warp_test(Arc::clone(&dev))?;

    // 4-step async pipeline test (product.2)
    tests_scaling::run_pipeline_test(Arc::clone(&dev))?;

    // Showcase demo kernel (product.4)
    tests_scaling::run_showcase_test(Arc::clone(&dev))?;

    // Multi-block scaling test (multiblock.1)
    tests_scaling::run_multi_block_test(Arc::clone(&dev))?;

    // Multi-block 512-thread scaling test (multiblock.2)
    tests_scaling::run_multi_block_512_test(Arc::clone(&dev))?;

    // Slab allocator deallocation test (allocator.2)
    tests_scaling::run_slab_dealloc_test(Arc::clone(&dev))?;

    // Concurrent slab allocator test (allocator.3)
    tests_scaling::run_slab_concurrent_test(Arc::clone(&dev))?;

    tests_scaling::run_println_direct_test(Arc::clone(&dev))?;

    tests_scaling::run_error_propagation_test(Arc::clone(&dev))?;

    tests_scaling::run_multi_block_async_test(Arc::clone(&dev))?;

    println!("\nAll tests PASSED.");
    Ok(())
}
